### PR TITLE
Added FPGA12x12 with CocoTB tests

### PR DESCRIPTION
**Pull request by ganeshgore**

### CODE REVIEW

**Review by tangxifan — CHANGES_REQUESTED** [review]
Remove all the .vcd files and set them to gitignore list.

**Comment by ganeshgore** [comment]
I kept them for reference

**Comment by tangxifan** [comment]
> I kept them for reference

What are the sizes of the vcd files? If they are large, I would not suggest uploading them. We can add sreenshots to documentation instead.

**Comment by ganeshgore** [comment]
Its not large (<1MB in worst case), It probes limited signals (Enough to demonstrate the success of the test).

**Review by tangxifan — APPROVED** [review]

**Pull request merged**
